use_frameworks!

platform :ios, '9.0'

target 'Reflex_Example' do
  pod 'Reflex', :path => '../'

  target 'Reflex_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
